language: python
python:
  - "2.7"
  - "3.5"
install:
  - "pip install flake8"
  - "pip install coveralls"
  - "pip install -r requirements.txt"
before_script:
  - "flake8 ."
script:
  - "coverage run -m unittest discover"
# after_success:
#   - "coveralls"
cache:
  directories:
    - $HOME/.cache/pip
