web:
  build: .
  ports:
   # HOST:CONTAINER
   - "5000:5000"
  volumes:
   - /tmp/authentication:/data
  environment:
   - SQLALCHEMY_DATABASE_URI=sqlite:////data/authentication.db
  command: python authentication/authentication.py